SELECTN USER_IDNFROMN DU_AD_DW.ADS_BUSINESS_USER_BRAND_ALGO_GROUPNWHEREN PT = '${bizdate}'N AND BRAND_ID = '1000524' N AND RANK_NUM*(
    SELECT
         COUNT(DISTINCT USER_TYPE)
    FROM
         DU_AD_DW.ADS_BUSINESS_USER_BRAND_ALGO_GROUP
    WHERE
          PT = '${bizdate}'
        AND DATA_TYPE = 'PRO'
) U003C= '100' N AND DATA_TYPE = 'PRO';